<?php
/**
 * Created by PhpStorm.
 * User: 15603
 * Date: 2018/5/30
 * Time: 14:18
 */

namespace app\admin\controller;



use think\Db;
use \app\admin\model\Article as Modelarticle;
use \app\api\controller\Common;
use \app\admin\model\Articlecategory;
use \app\admin\model\Findfine;
use \app\admin\model\Outnews;


class Article extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    /*
     * 文章列表
     * */
    public function index(){

        $article = Modelarticle::where('deletetime',0)->paginate(10);

        if($article){
            $this->assign('article',$article);
        }
        return $this->fetch('/article/articlelist');
    }


    /*
     * 新增文章
     * */

    public function add(){
        $category = Articlecategory::all();
        $this->assign('category',$category);
        return $this->fetch('/article/articleadd');
    }

    /*
     * 文章修改
     * */

    public function edit($id){
        $category = Articlecategory::all();
        $this->assign('category',$category);
        $article = Modelarticle::where('id',$id)->find();
        if(!$article){
            return '页面不存在';
        }
        $this->assign('article',$article);
        return $this->fetch('/article/articleedit');

    }



    /*
     * 发现美好
     * */
    public function findfine(){

        $findfine = Findfine::where('deletetime',0)->paginate(10);

        if($findfine){
            $this->assign('findfine',$findfine);
        }
        return $this->fetch('/right/findfinelist');
    }


    /*
     * 发现美好新增
     * */

    public function findfineadd(){
        return $this->fetch('/right/findfineadd');
    }

    /*
     * 发现美好修改
     * */

    public function findfineedit($id){

        $findfine = Findfine::where('id',$id)->find();
        if(!$findfine){
            return '页面不存在';
        }
        $this->assign('findfine',$findfine);
        return $this->fetch('/right/findfineedit');

    }



    /*
     * 外连信息港
     * */
    public function outnews(){

        $outnews = Outnews::where('deletetime',0)->paginate(10);

        if($outnews){
            $this->assign('outnews',$outnews);
        }
        return $this->fetch('/right/wailianlist');
    }


    /*
     * 外连信息港新增
     * */

    public function outnewsadd()
    {
        return $this->fetch('/right/wailianadd');
    }
    /*
     * 外连信息港修改
     * */

    public function outnewsedit($id){
        $outnews = Outnews::where('id',$id)->find();
        if(!$outnews){
            return '页面不存在';
        }
        $this->assign('outnews',$outnews);
            return $this->fetch('/right/wailianedit');

    }

}