<?php
/**
 * Created by PhpStorm.
 * User: 15603
 * Date: 2018/5/30
 * Time: 14:18
 */

namespace app\admin\controller;



use think\Db;
use \app\admin\model\User;
use \app\api\controller\Common;



class Index extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function index(){


      return $this->fetch('/index');
    }

    //登出
    public function out(){

        session('admin_username', null);
        session('admin_pic', null);
        $this->redirect('/admin/login');
    }

    /*
     * 用户列表
     * */
    public function userlist(){
        $users = User::where('isdel',0)->paginate(10);
        if($users){
            $this->assign('users',$users);
        }
        return $this->fetch('/user/userlist');
    }
    /*
     * 新增用户
     * */
    public function useradd(){

        return $this->fetch('/user/useradd');
    }
    /*
     * 查看用户
     * */
    public function usersee($id){
        $user = User::where(['isdel'=>0,'id'=>$id])->find();

        if(!$user){
            return '用户不存在';
        }
        $user['password'] = base64_decode($user['password']);
        $this->assign('user',$user);

        return $this->fetch('/user/usersee');
    }

    /*
     * 用户修改
     *
     * */
    public function useredit($id){
        $user = User::where(['isdel'=>0,'id'=>$id])->find();

        if(!$user){
            return '用户不存在';
        }
        $user['password'] = base64_decode($user['password']);
        $this->assign('user',$user);

        return $this->fetch('/user/useredit');
    }





}